In [110]:
import pandas as pd
import numpy as np

people = {
    'first': ['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'],
    'last': ['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, np.nan, 'Missing'],
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com',
              'JohnDoe@email.com', None, np.nan, None, 'Missing'],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}

df=pd.DataFrame(people)
df.replace('Missing', np.nan, inplace=True)
df.replace('NA', np.nan, inplace=True)

In [111]:
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True   True   True
6   True   True   True   True

In [112]:
#Display all missing values
df.fillna('Missing')

     first     last                    email      age
0    Corey  Schafer  CoreyMSchafer@gmail.com       33
1     Jane      Doe        JaneDoe@email.com       55
2     John      Doe        JohnDoe@email.com       63
3    Chris  Schafer                  Missing       36
4  Missing  Missing                  Missing  Missing
5  Missing  Missing                  Missing  Missing
6  Missing  Missing                  Missing  Missing

In [113]:
#Count the number of missing values in each column.
df.isnull().sum()

first    3
last     3
email    4
age      3
dtype: int64

In [114]:
#Count the total number of missing values in the entire DataFrame.
df.isna().sum().sum()

13

In [115]:
#Show only rows that contain at least one missing value.
df.isna().any()

first    True
last     True
email    True
age      True
dtype: bool

In [116]:
#Show only rows with no missing values.
df.isna().all(axis=0)

first    False
last     False
email    False
age      False
dtype: bool

In [117]:
#Replace all missing values with:
df.fillna('UNKNOWN')

     first     last                    email      age
0    Corey  Schafer  CoreyMSchafer@gmail.com       33
1     Jane      Doe        JaneDoe@email.com       55
2     John      Doe        JohnDoe@email.com       63
3    Chris  Schafer                  UNKNOWN       36
4  UNKNOWN  UNKNOWN                  UNKNOWN  UNKNOWN
5  UNKNOWN  UNKNOWN                  UNKNOWN  UNKNOWN
6  UNKNOWN  UNKNOWN                  UNKNOWN  UNKNOWN

In [118]:
#replace missing emails with no email
df['email'] = df['email'].fillna('No Email')

In [119]:
df

   first     last                    email   age
0  Corey  Schafer  CoreyMSchafer@gmail.com    33
1   Jane      Doe        JaneDoe@email.com    55
2   John      Doe        JohnDoe@email.com    63
3  Chris  Schafer                 No Email    36
4    NaN      NaN                 No Email  None
5   None      NaN                 No Email  None
6    NaN      NaN                 No Email   NaN

In [120]:
#replace missing ages with 0
df['age']=df['age'].fillna(0)
df

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63
3  Chris  Schafer                 No Email  36
4    NaN      NaN                 No Email   0
5   None      NaN                 No Email   0
6    NaN      NaN                 No Email   0

In [121]:
#checking data type for the dataframe
df.dtypes

first    object
last     object
email    object
age      object
dtype: object

In [126]:
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4   True   True  False  False
5   True   True  False  False
6   True   True  False  False

In [125]:
df.isna().sum()

first    3
last     3
email    0
age      0
dtype: int64

In [129]:
#Show only rows that contain at least one missing value.
df.isna().any()

first     True
last      True
email    False
age      False
dtype: bool

In [132]:
#Show only rows that contain no missing values
df.isna().all()

first    False
last     False
email    False
age      False
dtype: bool

In [144]:
#Count missing values in each colum
df.isna().sum()

first    3
last     3
email    0
age      0
dtype: int64

In [145]:
#Count total missing values in the DataFrame.
df.isna().sum().sum()

6

In [152]:
#Drop rows containing any missing value.
df.dropna()

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63
3  Chris  Schafer                 No Email  36

In [153]:
#Drop rows only if all values are missing.
df.dropna('how=all')

TypeError: DataFrame.dropna() takes 1 positional argument but 2 were given

In [ ]:
#Convert the age column to numeric.
df['age']= df['age'].astype('float')

In [162]:
#Calculate average age.
df['age'].mean()

26.714285714285715

In [163]:
#Calculate maximum age.
df['age'].max()

63.0

In [164]:
#Calculate minimum age.
df['age'].min()

0.0

In [171]:
#Show everyone older than 40.
df[df['age']>40]

  first last              email   age
1  Jane  Doe  JaneDoe@email.com  55.0
2  John  Doe  JohnDoe@email.com  63.0

In [178]:
#Show everyone younger than the average age.
df[df['age']<df['age'].mean()]

  first last     email  age
4   NaN  NaN  No Email  0.0
5  None  NaN  No Email  0.0
6   NaN  NaN  No Email  0.0

In [179]:
#Show everyone older than the average age.
df[df['age']>df['age'].mean()]

   first     last                    email   age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33.0
1   Jane      Doe        JaneDoe@email.com  55.0
2   John      Doe        JohnDoe@email.com  63.0
3  Chris  Schafer                 No Email  36.0

In [ ]:
#Show all unique first names.
df['first'].unique()

array(['Schafer', 'Doe', nan], dtype=object)

In [182]:
#Count the number of unique first names.
df['first'].nunique()

4

In [183]:
#Count how many times each first name appears.
df['first'].value_counts()

first
Corey    1
Jane     1
John     1
Chris    1
Name: count, dtype: int64

In [184]:
#Count how many times each age appears.
df['age'].value_counts()

age
0.0     3
33.0    1
55.0    1
63.0    1
36.0    1
Name: count, dtype: int64

In [185]:
df.isna().sum()

first    3
last     3
email    0
age      0
dtype: int64