In [1]:
import pandas as pd

In [2]:

people = {
    "first": ["Corey", "Jane", "John", "Sarah", "Mike", "Emma"],
    "last": ["Schafer", "Doe", "Doe", "Smith", "Johnson", "Brown"],
    "age": [35, 28, 42, 19, 31, 24],
    "country": ["USA", "Canada", "USA", "UK", "Canada", "USA"],
    "salary": [85000, 65000, 95000, 30000, 72000, 55000]
}

In [51]:
df = pd.DataFrame(people)

In [67]:
#People from the USA
filt = df['country'] == 'USA'
#PEOPLE ABOVE 30
unc = df['age'] > 30
#people earning more than 70000
racks = df['salary'] > 70000
#people only from canada
can = df['country'] == 'Canada'
#people younger than 25
jeets = df['age'] < 25
#people  earning more than 60000
sixty_racks = df['salary']> 60000
#people younger than 30
Mille= df['age'] < 30
#people above 25 
boom = df['age'] >25 
#people below 40
alpha = df['age'] < 40

In [18]:
df.loc[filt]

   first     last  age country  salary
0  Corey  Schafer   35     USA   85000
2   John      Doe   42     USA   95000
5   Emma    Brown   24     USA   55000

In [52]:
#PEOPLE ABOVE 30
df.loc[unc]

   first     last  age country  salary
0  Corey  Schafer   35     USA   85000
2   John      Doe   42     USA   95000
4   Mike  Johnson   31  Canada   72000

In [53]:
#people earning more than 70000
df.loc[racks]

   first     last  age country  salary
0  Corey  Schafer   35     USA   85000
2   John      Doe   42     USA   95000
4   Mike  Johnson   31  Canada   72000

In [54]:
#people only from canada
df.loc[can]

  first     last  age country  salary
1  Jane      Doe   28  Canada   65000
4  Mike  Johnson   31  Canada   72000

In [55]:
#people younger than 25
df.loc[jeets]

   first   last  age country  salary
3  Sarah  Smith   19      UK   30000
5   Emma  Brown   24     USA   55000

In [32]:
#people from canada and older than 30
df.loc[can & unc]

  first     last  age country  salary
4  Mike  Johnson   31  Canada   72000

In [56]:
#people from USA and earning more than 60000
df.loc[filt & sixty_racks]

   first     last  age country  salary
0  Corey  Schafer   35     USA   85000
2   John      Doe   42     USA   95000

In [57]:
#Show people from Canada AND earning more than 70000.
df.loc[can & racks]

  first     last  age country  salary
4  Mike  Johnson   31  Canada   72000

In [59]:
#Show people from USA AND younger than 30.
df.loc[filt & Mille]

  first   last  age country  salary
5  Emma  Brown   24     USA   55000

In [61]:
#Show people from USA OR Canada.
df.loc[filt | can]

   first     last  age country  salary
0  Corey  Schafer   35     USA   85000
1   Jane      Doe   28  Canada   65000
2   John      Doe   42     USA   95000
4   Mike  Johnson   31  Canada   72000
5   Emma    Brown   24     USA   55000

In [68]:
#Show people whose:age > 25, age < 40
df.loc[boom & alpha ]

   first     last  age country  salary
0  Corey  Schafer   35     USA   85000
1   Jane      Doe   28  Canada   65000
4   Mike  Johnson   31  Canada   72000

In [74]:
#Show people from:Canada, UK, using a method that doesn't require writing two separate country comparisons.
df.loc[~filt]

   first     last  age country  salary
1   Jane      Doe   28  Canada   65000
3  Sarah    Smith   19      UK   30000
4   Mike  Johnson   31  Canada   72000

In [ ]:
#Show only:first country for people older than 30.
df.loc[ unc, ['first' , 'country']]

   first country
0  Corey     USA
2   John     USA
4   Mike  Canada

In [ ]:
#Exercise 17 Show only: first salary for people from Canada.
df.loc[can,['first','salary']]

  first  salary
1  Jane   65000
4  Mike   72000

In [77]:
# Exercise 18 Show only: first age salary for people from USA earning more than 60000.
df.loc[filt & sixty_racks, ['first','age','salary']]

   first  age  salary
0  Corey   35   85000
2   John   42   95000

In [81]:
#Exercise 2Show only:first country for people who satisfy:country is USA OR Canada age > 25
df.loc[(filt | can) & boom, ['first','country']]

   first country
0  Corey     USA
1   Jane  Canada
2   John     USA
4   Mike  Canada