In [2]:
import pandas as pd
df = pd.read_csv('data/results.csv')
schema_df = pd.read_csv('data/schema.csv')
pd.set_option('display.max_column', 172)
pd.set_option('display.max_row', 85)
df.rename(columns={'ConvertedCompYearly':'Salary'}, inplace = True)
df.head(10)

C:\Users\casey\AppData\Local\Temp\ipykernel_29628\3203966957.py:2: DtypeWarning: Columns (56,74,92,97,98,105,109,110,132,162,165) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/results.csv')

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,Salary,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
5,6,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc....",15.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,20.0,"Developer, back-end",NaN,NaN,NaN,"Yes, I influenced the purchase of a substantia...",Work,12.0,5.0,4.0,6.0,2.0,10.0,3.0,7.0,8.0,14.0,NaN,12.0,5.0,13.0,10.0,9.0,1.0,4.0,6.0,2.0,15.0,NaN,Fintech,4.0,3.0,5.0,8.0,9.0,2.0,1.0,10.0,11.0,12.0,6.0,13.0,14.0,15.0,7.0,NaN,I'm not sure,I have somewhat considered changing my career ...,5.0,5.0,Ukraine,USD United States dollar,120000.0,Yes,Java;Scala,Java;Kotlin;Scala,Java;Scala,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud;Microso...,Amazon Web Services (AWS),Amazon Web Services (AWS),NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,akka,akka,Yes,IntelliJ IDEA;Visual Studio Code,IntelliJ IDEA;Visual Studio Code,IntelliJ IDEA;Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MacOS,MacOS,Azure Devops;GitHub;GitLab;Jira,GitHub;Jira,GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;X;YouTube;Linked...,Stack Overflow;Stack Exchange;X;YouTube;Linked...,Stack Overflow;Stack Exchange;X;YouTube;Linked...,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 10 and 15 years,"Infrequently, less than once per year","Lists of recommendations (tools, frameworks, t...",6.0,NaN,9.0,3.0,4.0,5.0,10.0,1.0,11.0,15.0,NaN,"Yes, somewhat","Rarely, almost never","Yes, I use AI tools daily",Indifferent,Somewhat distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Predictive analytics,Deployment and monitoring,Project planning;Debugging or fixing code;Comm...,Testing code;Learning new concepts or technolo...,"AI solutions that are almost right, but not quite",No it isnt,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering;Business process automati...,NaN,AI agents have increased my productivity.;AI a...,NaN,AI agents have improved the quality of my code...,AI agents have helped me automate repetitive t...,NaN,The cost of using certain AI agent platforms i...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,GitHub Copilot,NaN,When I have ethical or security concerns about...,designing the architecture in the new domain,120000.0,7.0

In [3]:
schema_df[schema_df['qname']=='ConvertedCompYearly']

Empty DataFrame
Columns: [qid, qname, question, type, sub, sq_id]
Index: []

In [4]:
#Find the average salary for each country.
df.groupby('Country')
df.groupby('Country')['Salary'].mean()

Country
Afghanistan                              12227.250000
Albania                                  47973.583333
Algeria                                  15935.400000
Andorra                                 208763.750000
Angola                                  149857.250000
                                            ...
Venezuela, Bolivarian Republic of...     17008.400000
Viet Nam                                189894.192982
Yemen                                    17582.500000
Zambia                                    6594.875000
Zimbabwe                                 25662.500000
Name: Salary, Length: 177, dtype: float64

In [5]:
#Find the max salary for each country.

df.groupby('Country')['Salary'].max()

Country
Afghanistan                               65000.0
Albania                                  139218.0
Algeria                                   98612.0
Andorra                                  400000.0
Angola                                   580073.0
                                          ...
Venezuela, Bolivarian Republic of...     114616.0
Viet Nam                                6000000.0
Yemen                                     83874.0
Zambia                                    30000.0
Zimbabwe                                  70000.0
Name: Salary, Length: 177, dtype: float64

In [6]:
#Find the min salary for each country.

df.groupby('Country')['Salary'].min()

Country
Afghanistan                               282.0
Albania                                     8.0
Algeria                                    17.0
Andorra                                 34804.0
Angola                                    200.0
                                         ...
Venezuela, Bolivarian Republic of...       12.0
Viet Nam                                    1.0
Yemen                                      21.0
Zambia                                    100.0
Zimbabwe                                 1800.0
Name: Salary, Length: 177, dtype: float64

In [7]:
#Count how many respondents belong to each country
df.groupby('Country')['Salary'].count().head(15)

Country
Afghanistan              8
Albania                 12
Algeria                 15
Andorra                  4
Angola                   4
Antigua and Barbuda      1
Argentina              160
Armenia                 11
Australia              569
Austria                280
Azerbaijan               9
Bahrain                  2
Bangladesh             120
Barbados                 2
Belarus                 16
Name: Salary, dtype: int64

In [8]:
#Find the total salary paid per country.
df.groupby('Country')['Salary'].sum().head(10)

Country
Afghanistan               97818.0
Albania                  575683.0
Algeria                  239031.0
Andorra                  835055.0
Angola                   599429.0
Antigua and Barbuda           1.0
Argentina               7403390.0
Armenia                  275180.0
Australia              65970664.0
Austria                22253735.0
Name: Salary, dtype: float64

In [9]:
#These are the most important GroupBy questions left. Q9
#For each country, find: mean salary, max salary, min salary
df.groupby('Country')['Salary'].agg(['mean', 'max', 'min'])

                                               mean        max      min
Country
Afghanistan                            12227.250000    65000.0    282.0
Albania                                47973.583333   139218.0      8.0
Algeria                                15935.400000    98612.0     17.0
Andorra                               208763.750000   400000.0  34804.0
Angola                                149857.250000   580073.0    200.0
...                                             ...        ...      ...
Venezuela, Bolivarian Republic of...   17008.400000   114616.0     12.0
Viet Nam                              189894.192982  6000000.0      1.0
Yemen                                  17582.500000    83874.0     21.0
Zambia                                  6594.875000    30000.0    100.0
Zimbabwe                               25662.500000    70000.0   1800.0

[177 rows x 3 columns]

In [10]:
df.groupby('Country')['Salary'].agg(['mean', 'max', 'min', 'count'])

                                               mean        max      min  count
Country
Afghanistan                            12227.250000    65000.0    282.0      8
Albania                                47973.583333   139218.0      8.0     12
Algeria                                15935.400000    98612.0     17.0     15
Andorra                               208763.750000   400000.0  34804.0      4
Angola                                149857.250000   580073.0    200.0      4
...                                             ...        ...      ...    ...
Venezuela, Bolivarian Republic of...   17008.400000   114616.0     12.0     35
Viet Nam                              189894.192982  6000000.0      1.0     57
Yemen                                  17582.500000    83874.0     21.0     10
Zambia                                  6594.875000    30000.0    100.0      8
Zimbabwe                               25662.500000    70000.0   1800.0      8

[177 rows x 4 columns]

In [11]:
#For each country, find:average Salary, average WorkExp
df.groupby('Country')[['Salary','WorkExp']].mean()

                                             Salary    WorkExp
Country
Afghanistan                            12227.250000  15.000000
Albania                                47973.583333  11.681818
Algeria                                15935.400000   7.342857
Andorra                               208763.750000  19.500000
Angola                                149857.250000   5.333333
...                                             ...        ...
Venezuela, Bolivarian Republic of...   17008.400000  13.977778
Viet Nam                              189894.192982   7.491228
Yemen                                  17582.500000   6.266667
Zambia                                  6594.875000   6.583333
Zimbabwe                               25662.500000  11.833333

[177 rows x 2 columns]

In [12]:
#Show only Canadian respondents.
df[df['Country']== 'Canada']

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,Salary,JobSat
75,76,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",15.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...","Other online resources (e.g. standard search, ...",17.0,"Developer, full-stack",100 to 499 employees,Individual contributor,"Your choice (very flexible, you can come in wh...",No,Work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software Development,3.0,1.0,2.0,10.0,11.0,8.0,4.0,12.0,5.0,7.0,6.0,13.0,14.0,15.0,9.0,NaN,No,I have neither consider or transitioned into a...,2.0,NaN,Canada,CAD Canadian dollar,100000.0,Yes,C++;PowerShell,Rust,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,APT;Docker;MSBuild;Ninja,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Notepad++;Visual Studio;Visual Studio Code,NaN,NaN,NaN,NaN,c++23,NaN,NaN,NaN,NaN,Windows,Windows,GitLab,NaN,NaN,NaN,NaN,Stack Overflow,Stack Overflow,Stack Overflow,NaN,NaN,NaN,NaN,NaN,NaN,Copilot integrated in visual studio,NaN,Yes,Daily or almost daily,Between 10 and 15 years,Less than once every 2 - 3 months,NaN,13.0,NaN,12.0,1.0,2.0,3.0,6.0,7.0,10.0,15.0,NaN,"Yes, somewhat","Rarely, almost never","Yes, I use AI tools monthly or infrequently",Favorable,Somewhat distrust,I don't use AI tools for complex tasks / I don...,NaN,Learning about a codebase;Project planning;Deb...,Writing code;Documenting code;Testing code;Sea...,NaN,NaN,"AI solutions that are almost right, but not qu...",NaN,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,72958.0,8.0
101,102,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc.)",15.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",NaN,20.0,"Developer, full-stack",Less than 20 employees,Individual contributor,Remote,"Yes, I endorsed a tool that was open-source an...",Work,13.0,2.0,6.0,8.0,1.0,10.0,4.0,9.0,7.0,14.0,NaN,14.0,8.0,9.0,7.0,10.0,2.0,3.0,1.0,12.0,15.0,NaN,Healthcare,12.0,1.0,3.0,14.0,7.0,13.0,9.0,6.0,8.0,11.0,10.0,4.0,5.0,15.0,2.0,NaN,No,I have neither consider or transitioned into a...,5.0,3.0,Canada,CAD Canadian dollar,110000.0,Yes,Bash/Shell (all shells);HTML/CSS;JavaScript;Po...,NaN,NaN,NaN,NaN,Yes,MySQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Docker;Microsoft Azu...,Vite;Yarn,NaN,NaN,NaN,Yes,Express;Node.js;React,NaN,NaN,NaN,NaN,Yes,Notepad++;Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MacOS;iOS;Linux (non-WSL);iPadOS,Windows;Windows Subsystem for Linux (WSL),GitHub;Jira;Markdown File;Monday.com,NaN,NaN,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per week,"More than 15 years, or since Stack Overflow st...",I have never participated in Q&A on Stack Over...,Long-form articles;Coding challenges;Logic gam...,14.0,NaN,2.0,15.0,4.0,10.0,5.0,11.0,12.0,1.0,Viewing Answers,"No, not at all",I don't use AI or AI-enabled tools,"No, but I plan to soon",Unfavorable,Highly distrust,I don't use AI tools for complex tasks / I don...,NaN,Learning about a codebase;Project planning;Deb...,Writing code;Documenting code;Search for answe...,NaN,NaN,I don’t use AI tools regularly,Absolutely not.,"No, but I plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Explaining a problem clearly and concisely. Un...,80254.0,9.0
103,104,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Volunteering (regularly),10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",Videos (not associated with specific online co...,15.0,"Developer, full-stack",20 to 99 employees,Individual contributor,Remote,"Yes, I influenced the purchase of a tool that ...",Work,9.0,1.0,10.0,2.0,6.0,7.0,12.0,11.0,4.0,14.0,NaN,11.0,4.0,14.0,8.0,6.0,1.0,2.0,10.0,13.0,15.0,NaN,Software Development,1.0,3.0,2.0,12.0,8.0,14.0,5.0,7.0,9.0,13.0,6.0,10.0,11.0,15.0,4.0,NaN,No,I have transitioned into a new career and/or i...,4.0,NaN,Canada,CAD Canadian dollar,150000.0,Yes,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...,JavaScript;Python;SQL;TypeScript,JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Dynamodb;Elasticsearch;H2;PostgreSQL;Redis,PostgreSQL;Redis,PostgreSQL;Redis,NaN,NaN,Yes,Amazon Web Services (AWS);Docker;Maven (build ...,Amazon Web Services (AWS);Docker;npm;Terraform...,Amazon Web Services (AWS);Docker;npm;Terraform...,NaN,NaN,Yes,Angular;AngularJS;Express;jQuery;Next.js;Node....,Angular;Express;Next.js;React,Angular;Express;Next.js;React,NaN,NaN,Yes,Cursor;Eclipse;Vim;Visual Studio Code,Visual Studio Code,Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,iOS,MacOS;iOS;Fedora,Confluence;GitHub;Google Workspace;Jira;Markdo...,Confluence;GitHub;Google Workspace;Jira;Linear...,Confluence;GitHub;Google Workspace;Jira;Markdo...,NaN,NaN,"Reddit;Hashnode;GitHub (public projects, not p...","Reddit;GitHub (public projects, not private re...","Reddit;GitHub (public projects, not private re...",NaN,NaN,Yes,Anthropic: Claude Sonnet;openAI GPT (chatbot m...,Anthropic: Claude Sonnet,Anthropic: Claude Sonnet,NaN,NaN,Yes,A few times per month or weekly,Between 10 and 15 years,"Infrequently, less than once per year",Long-form articles;Videos,7.0,NaN,9.0,1.0,5.0,6.0,3.0,2.0,11.0,15.0,NaN,"No, not really",Less than half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,NaN,Project planning;Deployment and monitoring;Cre...,Testing code;Predictive analytics,Search for answers,"AI solutions that are almost right, but not quite",NaN,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have improved collaboration within m...,NaN,AI agents have helped me automate repetitive t...,NaN,NaN,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,pgvector,NaN,NaN,NaN,NaN,NaN,ChatGPT;GitHub Copilot;Perplexity,NaN,When I don’t trust AI’s answers;When I want to...,NaN,109438.0,8.0
120,121,"I am not primarily a developer, but I write co...",45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...","Other online resources (e.g. standard search, ...",25.0,Other (please specify):,500 to 999 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I influenced the purchase of a tool that ...",Work,8.0,2.0,5.0,10.0,1.0,11.0,9.0,13.0,12.0,14.0,NaN,10.0,1.0,6.0,13.0,3.0,11.0,2.0,14.0,4.0,15.0,NaN,Higher Education,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I'm not sure,I have neither consider or transitioned into a...,5.0,5.0,Canada,CAD Canadian dollar,98000.0,Yes,Bash/Shell (all shells);C++;COBOL;HTML/CSS;Jav...,Bash/Shell (all shells);C++;HTML/CSS;Java;Java...,Bash/Shell (all shells);C++;HTML/CSS;Java;Java...,NaN,NaN,Yes,MariaDB;Microsoft Access;Microsoft SQL Server;...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Ora...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Ora...,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,ASP.NET;Express;jQuery;Node.js;Ruby on Rails;V...,Angular;AngularJS;Express;jQuery;Laravel;Node....,Express;jQuery;Node.js;Vue.js;WordPress,NaN,NaN,Yes,Android Studio;Eclipse;IntelliJ IDEA;Notepad++...,Eclipse;IntelliJ IDEA;Notepad++;PyCharm;Vim;Vi...,Eclipse;IntelliJ IDEA;Notepad++;Vim;Visual Stu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;Android;Windows Subsystem for Linux (WSL),Windows;Ubuntu;Android;Windows Subsystem for L...,GitHub;GitLab,GitHub;GitLab,GitHub;GitLab,NaN,NaN,"Stack Overflow;GitHub (public projects, not pr...","Stack Overflow;GitHub (public projects, not pr...","Stack Overflow;GitHub (public projects, not pr...",NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 10 and 15 years,"Infrequently, less than once per year",NaN,14.0,NaN,7.0,6.0,1.0,9.0,13.0,5.0,10.0,15.0,NaN,Neutral,I don't use AI or AI-enabled tools,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Writing code,Project planning;Committing and reviewing code...,Documenting code,Learning about a codebase,Debugging or fixing code;Testing code;Search f...,I haven’t encountered any problems,no,"No, and I don't plan to","No, but my development work has significantly ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,problem solving\ndebugging\ntesting\nfine tuni...,71499.0,NaN
122,123,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),22.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,27.0,"Developer, full-stack","1,000 to 4,999 employees",Individual contributor,Remote,No,Personal Project,1.0,5.0,9.0,12.0,4.0,6.0,7.0,10.0,8.0,14.0,NaN,14.0,8.0,2.0,4.0,1.0,9.0,12.0,13.0,10.0,15.0,NaN,Manufacturing,9.0,10.0,12.0,1.0,7.0,2.0,3.0,11.0,4.0,5.0,6.0,14.0,8.0,15.0,13.0,NaN,No,I have neither consider or transitioned into a...,10.0,4.0,Canada,CAD Canadian dollar,90000.0,Yes,Bash/Shell (all shells);C#;Java;JavaScript;Kot...,NaN,NaN,NaN,NaN,Yes,Cassandra;Elasticsearch;Firebase Realtime Data...,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Chocolatey;Composer;...,NaN,NaN,Fleet,NaN,Yes,ASP.NET;ASP.NET Core;jQuery;Laravel;Next.js;No...,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;Android;iOS;iPadOS,Windows;MacOS;iOS;iPadOS,Azure Devops;Confluence;Google Workspace;Jira;...,NaN,NaN,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 10 and 15 years,"Infrequently, less than once per year",NaN,4.0,NaN,14.0,11.0,2.0,1.0,8.0,9.0,6.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools daily",Very favorable,Neither trust nor distrust,Neither good or bad at handling complex tasks,NaN,Learning about a codebase;Predictive analytics...,Project planning;Documenting code;Debugging or...,Writing code;Committing and reviewing code;Sea...,NaN,Debugging AI-generated code is more time-consu...,No,"No, and I don't plan to","Yes, somewhat",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,65663.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48828,48829,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,1.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...","Other online resources (e.g. standard search, ...",5.0,"Developer, embedded applications or devices",500 to 999 employees,Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I influenced the purchase of a substantia...",Work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Healthcare,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Canada,CAD Canadian dollar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48834,48835,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,30.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Colleague or on-the-job training;Blogs or podc...,38.0,"Developer, mobile","5,000 to 9,999 employees",Individual contributor,Remote,"Yes, I influenced the purchase of a tool that ...",Work,9.0,7.0,5.0,3.0,2.0,1.0,6.0,4.0,8.0,10.0,NaN,9.0,5.0,6.0,2.0,1.0,4.0,7.0,3.0,8.0,10.0,NaN,Insurance,6.0,2.0,10.0,14.0,12.0,5.0,3.0,11.0,1.0,4.0,8.0,9.0,7.0,15.0,13.0,NaN,No,I have neither consider or transitioned into a...,2.0,3.0,Canada,CAD Canadian dollar,145000.0,Yes,Bash/Shell (all shells);C;C#;C++;Java;JavaScri...,Bash/Shell (all shells);C#;C++;Kotlin;Swift,Bash/Shell (all shells);C#;C++;Kotlin;Swift,NaN,NaN,Yes,Microsoft SQL Server;MySQL;SQLite,MySQL;SQLite,MySQL;SQLite,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,Android Studio;Notepad++;Visual Studio;Visual ...,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ubuntu;Debian,Windows;MacOS;iOS,Confluence;GitHub;Jira;Wikis,Confluence;GitHub;Jira;Wikis,Confluence;GitHub;Jira;Wikis,NaN,NaN,Stack Overflow;Stack Exchange,Stack Overflow;Stack Exchange,Stack Overflow;Stack Exchange,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Multiple times per day,"More than 15 years, or since Stack Overflow st...",Less than once every 2 - 3 months,Long-form articles;Coding challenges;Logic gam...,1.0,2.0,3.0,7.0,9.0,5.0,4.0,6.0,8.0,10.0,NaN,"No, not really",I don't use AI or AI-enabled tools,"Yes, I use AI tools monthly or infrequently",Favorable,Somewhat distrust,Very poor at handling complex tasks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105790.0,9.0

In [13]:
#Q13 Show only respondents from the United States earning more than $100,000. Use: Country Salary
df[(df['Country'] == 'United States of America') & (df['Salary'] > 10000)]

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,Salary,JobSat
22,23,I am a developer by profession,25-34 years old,Some college/university study without earning ...,Employed,None of the above,7.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Colleague or on-the-job training,11.0,"Developer, full-stack",100 to 499 employees,Individual contributor,Remote,"Yes, I influenced the purchase of a tool that ...",Work,13.0,3.0,9.0,10.0,1.0,11.0,4.0,2.0,5.0,14.0,NaN,14.0,2.0,8.0,12.0,4.0,1.0,13.0,10.0,3.0,15.0,NaN,Fintech,3.0,2.0,4.0,6.0,9.0,10.0,5.0,11.0,8.0,12.0,1.0,13.0,14.0,15.0,7.0,NaN,I'm not sure,I have somewhat considered changing my career ...,5.0,10.0,United States of America,USD United States dollar,87500.0,Yes,C#;C++;JavaScript;Python;Visual Basic (.Net),C#;Python,C#;Python,NaN,NaN,Yes,Microsoft SQL Server,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud;Microso...,Microsoft Azure,Microsoft Azure,NaN,NaN,Yes,ASP.NET;ASP.NET Core;jQuery,ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,NaN,NaN,Yes,Notepad++;PyCharm;Visual Studio;Visual Studio ...,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows,Windows,Azure Devops;GitHub;Obsidian;Stack Overflow fo...,Azure Devops;GitHub;Obsidian,Azure Devops;GitHub;Obsidian,NaN,NaN,Stack Overflow;Stack Exchange;Discord;Reddit;H...,Stack Overflow;Stack Exchange;Discord;Reddit;H...,Stack Overflow;Stack Exchange;Discord;Reddit;H...,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Multiple times per day,Between 5 and 10 years,Less than once every 2 - 3 months,"Lists of recommendations (tools, frameworks, t...",4.0,NaN,8.0,1.0,12.0,11.0,10.0,2.0,9.0,15.0,NaN,"Yes, definitely","Rarely, almost never","Yes, I use AI tools monthly or infrequently",Unfavorable,Somewhat distrust,Bad at handling complex tasks,Writing code,Learning about a codebase;Project planning;Doc...,Debugging or fixing code;Creating or maintaini...,Predictive analytics,NaN,"AI solutions that are almost right, but not qu...","No. I find it to be useless, unless I'm starti...","No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,NaN,I am concerned about the accuracy of the infor...,My company's IT and/or InfoSec teams have stri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Technical knowledge. As AI slides into the for...,87500.0,9.0
29,30,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (10-19 hours per week),19.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Technical ...,15.0,"Developer, mobile",500 to 999 employees,Individual contributor,Remote,"Yes, I influenced the purchase of a tool that ...",Work,9.0,3.0,4.0,8.0,11.0,7.0,5.0,1.0,10.0,14.0,NaN,12.0,4.0,5.0,9.0,14.0,7.0,11.0,6.0,2.0,15.0,NaN,Software Development,7.0,6.0,9.0,10.0,11.0,12.0,13.0,5.0,14.0,8.0,1.0,3.0,4.0,15.0,2.0,NaN,No,I have neither consider or transitioned into a...,6.0,6.0,United States of America,USD United States dollar,205000.0,Yes,Bash/Shell (all shells);C;C#;C++;Java;JavaScri...,NaN,NaN,NaN,NaN,Yes,MySQL;PostgreSQL;SQLite;Supabase,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Digital O...,NaN,NaN,NaN,NaN,Yes,Next.js;Node.js;React,NaN,NaN,"Remix, Capacitor, Ionic",NaN,Yes,Android Studio;Claude Code;Cursor;IntelliJ IDE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;Linux (non-WSL),Windows;MacOS;Android;Linux (non-WSL),GitHub;GitLab;Google Workspace;Jira;Notion;Tre...,NaN,NaN,NaN,NaN,Discord;Reddit;Hacker News;GitHub (public proj...,NaN,NaN,NaN,NaN,Yes,Anthropic: Claude Sonnet;openAI Reasoning models,NaN,NaN,NaN,NaN,Yes,Less than once per month or monthly,Between 10 and 15 years,"Infrequently, less than once per year",Chat (bot/AI),10.0,NaN,9.0,6.0,1.0,5.0,13.0,12.0,8.0,15.0,NaN,"No, not really",About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat distrust,Very poor at handling complex tasks,Writing code;Learning new concepts or technolo...,Project planning;Deployment and monitoring;Pre...,Learning about a codebase;Testing code,Committing and reviewing code;Creating or main...,Documenting code;Debugging or fixing code;Sear...,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,It takes significant time and effort to learn ...,I am concerned about the accuracy of the infor...,NaN,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Being able to make sure the AI code is correct...,205000.0,8.0
31,32,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,17.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",NaN,23.0,"Developer, full-stack",100 to 499 employees,Individual contributor,Remote,"Yes, I influenced the purchase of a tool that ...",Work,13.0,3.0,6.0,11.0,10.0,9.0,8.0,2.0,1.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fintech,2.0,3.0,4.0,11.0,12.0,5.0,6.0,10.0,7.0,8.0,9.0,13.0,14.0,15.0,1.0,NaN,No,I have neither consider or transitioned into a...,5.0,8.0,United States of America,USD United States dollar,250000.0,Yes,Elixir;HTML/CSS;JavaScript;SQL;TypeScript,Elixir;HTML/CSS;OCaml;Gleam,Elixir;HTML/CSS,NaN,NaN,Yes,BigQuery;Elasticsearch;PostgreSQL;SQLite,SQLite,SQLite,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Datadog;D...,Cloudflare;Homebrew;Make,Cloudflare;Homebrew;Make,hex,hex,Yes,Node.js;Phoenix;React,Phoenix,Phoenix,NaN,NaN,Yes,NaN,NaN,NaN,emacs,emacs,Tailwind CSS 4;Large Language Model,Tailwind CSS 4,Tailwind CSS 4,NaN,NaN,MacOS,MacOS,Airtable;Confluence;GitHub;Google Workspace;Ji...,NaN,NaN,NaN,NaN,Reddit;Dev.to;Hacker News;GitHub (public proje...,"GitHub (public projects, not private repos);Sl...","GitHub (public projects, not private repos);Sl...",NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 10 and 15 years,I have never participated in Q&A on Stack Over...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No, not at all",I don't use AI or AI-enabled tools,"No, and I don't plan to",Very unfavorable,Highly distrust,I don't use AI tools for complex tasks / I don...,NaN,NaN,NaN,NaN,NaN,I don’t use AI tools regularly,no,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,NaN,250000.0,8.0
33,34,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,24.0,"Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;Technical doc...,"No, I didn't spend time learning in the past year",NaN,26.0,Data engineer,"5,000 to 9,999 employees",Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I influenced the purchase of a substantia...",Work,10.0,5.0,4.0,7.0,2.0,11.0,8.0,3.0,1.0,14.0,NaN,12.0,2.0,5.0,1.0,9.0,8.0,3.0,4.0,14.0,15.0,NaN,Software Development,3.0,4.0,11.0,14.0,13.0,8.0,12.0,1.0,6.0,7.0,2.0,9.0,10.0,15.0,5.0,NaN,No,I have neither consider or transitioned into a...,3.0,0.0,United States of America,USD United States dollar,175000.0,Yes,C#;Python;SQL,NaN,NaN,NaN,NaN,Yes,Microsoft SQL Server,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Microsoft Azure;Terr...,NaN,NaN,NaN,NaN,Yes,ASP.NET;ASP.NET Core,NaN,NaN,NaN,NaN,Yes,Visual Studio;Visual Studio Code,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Windows Subsystem for Linux (WSL);Linu...,Azure Devops;Jira,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 10 and 15 years,A few times per month or weekly,NaN,6.0,NaN,8.0,12.0,7.0,4.0,5.0,2.0,10.0,15.0,NaN,"Yes, somewhat","Rarely, almost never","No, and I don't plan to",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,I don’t use AI tools regularly,no,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,business logic,175000.0,8.0
37,38,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (20-29 hours per week),15.0,"No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",NaN,25.0,"Developer, full-stack","10,000 or more employees",Individual contributor,In-person,"Yes, I influenced the purchase of a substantia...",Work,13.0,10.0,11.0,7.0,2.0,12.0,8.0,5.0,1.0,14.0,NaN,14.0,4.0,10.0,11.0,7.0,1.0,6.0,8.0,2.0,15.0,NaN,Government,3.0,5.0,7.0,6.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,4.0,2.0,15.0,1.0,NaN,No,I have neither consider or transitioned into a...,20.0,20.0,United States of America,USD United States dollar,109000.0,Yes,Ada;Assembly;Bash/Shell (all shells);C;C#;C++;...,NaN,NaN,NaN,NaN,Yes,MySQL;Oracle;PostgreSQL;SQLite,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,c++23,NaN,NaN,NaN,NaN,Windows;Ubuntu;Windows Subsystem for Linux (WS...,NaN,Doxygen;GitHub;Microsoft Planner,NaN,NaN,NaN,NaN,Stack Overflow;Discord;Reddit;GitHub (public p...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Daily or almost daily,"More than 15 years, or since Stack Overflow st...",Multiple times per day,NaN,6.0,NaN,3.0,5.0,7.0,1.0,14.0,2.0,10.0,15.0,NaN,"Yes, definitely",I don't use AI or AI-enabled tools,"No, and I don't plan to",Very unfavorable,Highly distrust,Very poor at handling complex tasks,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,"AI solutions that are almost right, but not qu...",LLM is useless to an experienced programmer an...,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other (please specify):,"I am paid for my knowledge, my knowledge canno...",109000.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49006,49007,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,14.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Videos (no...,14.0,"Developer, back-end",100 to 499 employees,Individual contributor,"Your choice (very flexible, you can come in wh...","Yes, I endorsed a tool that was open-source an...",Work,8.0,1.0,5.0,9.0,2.0,4.0,7.0,3.0,6.0,10.0,NaN,7.0,1.0,2.0,3.0,4.0,8.0,6.0,5.0,9.0,10.0,NaN,Fintech,8.0,3.0,7.0,11.0,14.0,10.0,6.0,9.0,5.0,4.0,2.0,13.0,12.0,15.0,1.0,NaN,No,I have transitioned into a new career and/or i...,18.0,10.0,United States of America,USD United States dollar,170000.0,Yes,HTML/CSS;JavaScript;Python;SQL;TypeScript,Go;Python;Rust,Python,NaN,NaN,Yes,Dynamodb;Elasticsearch;MongoDB;MySQL;PostgreSQ...,Elasticsearch;PostgreSQL;Redis,Elasticsearch;PostgreSQL;Redis,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Digital Ocea...,Digital Ocean;Docker;Netlify;Pip,Digital Ocean;Docker;Pip,NaN,NaN,Yes,Django;FastAPI;Next.js;React;Vue.js,Django;FastAPI;Svelte;Vue.js,Django;FastAPI;Vue.js,AlpineJS,NaN,Yes,Visual Studio Code;Windsurf,Claude Code;Visual Studio Code;Windsurf,Visual Studio Code;Windsurf,NaN,NaN,Large Language Model;Pydantic;RAG,Large Language Model;Pydantic;RAG;LangGraph;uv,Large Language Model;Pydantic;RAG,NaN,NaN,Windows;MacOS,MacOS,GitHub;GitLab;Jira;Lucid (includes Lucidchart),GitHub;GitLab,GitHub;GitLab,BitBucket,NaN,"Stack Overflow;GitHub (public projects, not pr...","Stack Overflow;GitHub (public projects, not pr...","Stack Overflow;GitHub (public projects, not pr...",NaN,NaN,Yes,Anthropic: Claude Sonnet;Gemini (Flash general...,Anthropic: Claude Sonnet;Gemini (Flash general...,Anthropic: Claude Sonnet;Gemini (Flash general...,NaN,NaN,Yes,A few times per month or weekly,Between 10 and 15 years,Less than once every 2 - 3 months,Job board,2.0,3.0,9.0,7.0,1.0,4.0,8.0,6.0,5.0,10.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Very favorable,Somewhat trust,Neither good or bad at handling complex tasks,Writing code;Committing and reviewing code;Sea...,Deployment and monitoring,Learning about a codebase;Project planning;Doc...,Testing code;Generating content or synthetic data,NaN,"AI solutions that are almost right, but not qu...",I'm exploring vibe coding through using IDE's ...,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Integration with external agents and APIs,AI agents have increased my productivity.;AI a...,AI agents have helped me solve complex problem...,AI agents have improved the quality of my code...,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,Llama Index;LangChain,NaN,Sentry,NaN,ChatGPT;GitHub Copilot;Google Gemini;Cody,NaN,When I want to fully understand something,"problem solving, performing complex tasks acro...",170000.0,7.0
49028,49029,"I am not primarily a developer, but I write co...",25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,5.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",NaN,8.0,Cybersecurity or InfoSec professional,"1,000 to 4,999 employees",Individual contributor,Remote,"Yes, I endorsed a tool that was ultimately not...",Work,10.0,5.0,4.0,8.0,1.0,3.0,9.0,7.0,2.0,6.0,Integration with existing tooling,10.0,8.0,6.0,4.0,1.0,2.0,5.0,3.0,7.0,9.0,NaN,Banking/Financial Services,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,I have somewhat considered changing my career ...,NaN,NaN,United States of America,USD United States dollar,77000.0,Yes,Bash/Shell (all shells);C#;Java;Python,Bash/Shell (all shells);C#;Java;Kotlin;Python,Bash/Shell (all shells);C#;Java;Python,Haskell,Haskell,Yes,Microsoft SQL Server,NaN,NaN,NaN,NaN,Yes,Microsoft Azure,Microsoft Azure,Microsoft Azure,Oracle,NaN,Yes,ASP.NET Core;Node.js,ASP.NET Core,ASP.NET Core,NaN,NaN,Yes,Visual Studio Code,Visual Studio Code;VSCodium,Visual Studio Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Linux (non-WSL),Windows,Azure Devops;GitHub;GitLab,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Reddit;GitHub (p...,Stack Overflow;Stack Exchange,Stack Overflow;Stack Exchange,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No, not at all",I don't use AI or AI-enabled tools,"No, and I don't plan to",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77000.0,NaN

In [14]:
df[df['Country'] == 'Canada']['Salary'].mean()

100143.3825136612