In [55]:
import pandas as pd

In [56]:
people = {
    "first": ["Corey", "Jane", "John", "Sarah", "Mike", "Emma"],
    "last": ["Schafer", "Doe", "Doe", "Smith", "Johnson", "Brown"],
    "age": [35, 28, 42, 19, 31, 24],
    "country": ["USA", "Canada", "USA", "UK", "Canada", "USA"],
    "salary": [85000, 65000, 95000, 30000, 72000, 55000],
}

In [57]:
df = pd.DataFrame(people)
df

   first     last  age country  salary
0  Corey  Schafer   35     USA   85000
1   Jane      Doe   28  Canada   65000
2   John      Doe   42     USA   95000
3  Sarah    Smith   19      UK   30000
4   Mike  Johnson   31  Canada   72000
5   Emma    Brown   24     USA   55000

In [58]:
df.rename(columns={'first' : 'first_name', 'last' : 'last_name', 'age' : 'age_youth', 'country' : 'home_land', 'salary' : 'racks_city'},inplace = True)

In [59]:
df

  first_name last_name  age_youth home_land  racks_city
0      Corey   Schafer         35       USA       85000
1       Jane       Doe         28    Canada       65000
2       John       Doe         42       USA       95000
3      Sarah     Smith         19        UK       30000
4       Mike   Johnson         31    Canada       72000
5       Emma     Brown         24       USA       55000

In [60]:
#CHAGNING THE COLUMN NAMES TO UPPERCASE
df.columns = [x.lower() for x in df.columns]
df

  first_name last_name  age_youth home_land  racks_city
0      Corey   Schafer         35       USA       85000
1       Jane       Doe         28    Canada       65000
2       John       Doe         42       USA       95000
3      Sarah     Smith         19        UK       30000
4       Mike   Johnson         31    Canada       72000
5       Emma     Brown         24       USA       55000

In [61]:
#Change the column names from underscore to having dash
df.columns = df.columns.str.replace('_','-')

In [62]:
df

  first-name last-name  age-youth home-land  racks-city
0      Corey   Schafer         35       USA       85000
1       Jane       Doe         28    Canada       65000
2       John       Doe         42       USA       95000
3      Sarah     Smith         19        UK       30000
4       Mike   Johnson         31    Canada       72000
5       Emma     Brown         24       USA       55000

In [63]:
#RENAMING COLUMNS FROM FROM RACK_CITY TO ANNUAL SALARY
df.rename(columns={'RACKS-CITY':'ANNUAL-SALARY'}, inplace=True)

In [64]:
df

  first-name last-name  age-youth home-land  racks-city
0      Corey   Schafer         35       USA       85000
1       Jane       Doe         28    Canada       65000
2       John       Doe         42       USA       95000
3      Sarah     Smith         19        UK       30000
4       Mike   Johnson         31    Canada       72000
5       Emma     Brown         24       USA       55000

In [65]:
#EXERCISE 1 RENAME FIRST-NAME TO FIRST, LASTNAME TO LAST, ANNUAL-SALARY TO SALARY
df.rename(columns={'first-name':'first','last-name':'last','racks-city':'salary'},inplace =True)

In [66]:
df

   first     last  age-youth home-land  salary
0  Corey  Schafer         35       USA   85000
1   Jane      Doe         28    Canada   65000
2   John      Doe         42       USA   95000
3  Sarah    Smith         19        UK   30000
4   Mike  Johnson         31    Canada   72000
5   Emma    Brown         24       USA   55000

In [67]:
#EXERCISE 2 CHANGE Change Sarah's age from 19 to 20
df.loc[3,'age-youth']=20

In [68]:
df

   first     last  age-youth home-land  salary
0  Corey  Schafer         35       USA   85000
1   Jane      Doe         28    Canada   65000
2   John      Doe         42       USA   95000
3  Sarah    Smith         20        UK   30000
4   Mike  Johnson         31    Canada   72000
5   Emma    Brown         24       USA   55000

In [69]:
#1. Change all UK values to United Kingdom
df.loc[df['home-land']== 'UK','home-land'] = 'USA'

In [70]:
df

   first     last  age-youth home-land  salary
0  Corey  Schafer         35       USA   85000
1   Jane      Doe         28    Canada   65000
2   John      Doe         42       USA   95000
3  Sarah    Smith         20       USA   30000
4   Mike  Johnson         31    Canada   72000
5   Emma    Brown         24       USA   55000

In [71]:
# Exercise 1 Rename only
df.rename(columns ={'first':'first_name','last':'last_name','age-youth':'age', 'home-land':'country'},inplace=True)

In [ ]:

df

  first_name last_name  age country  salary
0      Corey   Schafer   35     USA   85000
1       Jane       Doe   28  Canada   65000
2       John       Doe   42     USA   95000
3      Sarah     Smith   20     USA   30000
4       Mike   Johnson   31  Canada   72000
5       Emma     Brown   24     USA   55000

In [73]:
#CHANGE SARAH AGE TO 19
df.loc[3,'age'] = 19

In [74]:
df

  first_name last_name  age country  salary
0      Corey   Schafer   35     USA   85000
1       Jane       Doe   28  Canada   65000
2       John       Doe   42     USA   95000
3      Sarah     Smith   19     USA   30000
4       Mike   Johnson   31  Canada   72000
5       Emma     Brown   24     USA   55000

In [75]:
#CHANGE MIKES COUNTRY TO USA
df.loc[4,'country']='USA'
df

  first_name last_name  age country  salary
0      Corey   Schafer   35     USA   85000
1       Jane       Doe   28  Canada   65000
2       John       Doe   42     USA   95000
3      Sarah     Smith   19     USA   30000
4       Mike   Johnson   31     USA   72000
5       Emma     Brown   24     USA   55000

In [76]:
#Change emma salary to 60000
df.loc[df['first_name']=='Emma','salary']=60000
df

  first_name last_name  age country  salary
0      Corey   Schafer   35     USA   85000
1       Jane       Doe   28  Canada   65000
2       John       Doe   42     USA   95000
3      Sarah     Smith   19     USA   30000
4       Mike   Johnson   31     USA   72000
5       Emma     Brown   24     USA   60000

In [78]:
#Change all USA salaries by +5000
df.loc[df['country'] == 'USA', 'salary'] +5000
df

  first_name last_name  age country  salary
0      Corey   Schafer   35     USA   85000
1       Jane       Doe   28  Canada   65000
2       John       Doe   42     USA   95000
3      Sarah     Smith   19     USA   30000
4       Mike   Johnson   31     USA   72000
5       Emma     Brown   24     USA   60000

In [ ]:
#Set every salary below 50000 to 50000
df.loc[df['salary'] <50000,'salary'] = 50000
df

  first_name last_name  age country  salary
0      Corey   Schafer   35     USA   85000
1       Jane       Doe   28  Canada   65000
2       John       Doe   42     USA   95000
3      Sarah     Smith   19     USA   50000
4       Mike   Johnson   31     USA   72000
5       Emma     Brown   24     USA   60000

In [ ]:
#make everything upper case for loc
df.columns=[x.upper()for x in df.columns]
df

  FIRST_NAME LAST_NAME  AGE COUNTRY  SALARY
0      Corey   Schafer   35     USA   85000
1       Jane       Doe   28  Canada   65000
2       John       Doe   42     USA   95000
3      Sarah     Smith   19     USA   50000
4       Mike   Johnson   31     USA   72000
5       Emma     Brown   24     USA   60000

In [91]:
#APPLY METHOD 
#Convert all first names to uppercas

df['FIRST_NAME'].apply(str.upper)

0    COREY
1     JANE
2     JOHN
3    SARAH
4     MIKE
5     EMMA
Name: FIRST_NAME, dtype: object

In [92]:
#Convert all last names to lowercase
df['LAST_NAME'].apply(str.lower)

0    schafer
1        doe
2        doe
3      smith
4    johnson
5      brown
Name: LAST_NAME, dtype: object

In [94]:
#Find the length of every first name
df['FIRST_NAME'].apply(len)

0    5
1    4
2    4
3    5
4    4
5    4
Name: FIRST_NAME, dtype: int64

In [100]:
#Add "Mr/Ms " before every first name
def title(x):
    
          return "Mr/Mrs" + x

df['FIRST_NAME'].apply(title)

0    Mr/MrsCorey
1     Mr/MrsJane
2     Mr/MrsJohn
3    Mr/MrsSarah
4     Mr/MrsMike
5     Mr/MrsEmma
Name: FIRST_NAME, dtype: object

In [102]:
#Create a column containing the first letter of each name
def first_letter(x):
    return x[0]

df['initial'] = df['FIRST_NAME'].apply(first_letter)
df

  FIRST_NAME LAST_NAME  AGE COUNTRY  SALARY initial
0      Corey   Schafer   35     USA   85000       C
1       Jane       Doe   28  Canada   65000       J
2       John       Doe   42     USA   95000       J
3      Sarah     Smith   19     USA   50000       S
4       Mike   Johnson   31     USA   72000       M
5       Emma     Brown   24     USA   60000       E

In [104]:
#Create a column of last name
def last_name(x):
    return x[0]

df['cred']= df['LAST_NAME'].apply(last_name)
df

  FIRST_NAME LAST_NAME  AGE COUNTRY  SALARY initial cred
0      Corey   Schafer   35     USA   85000       C    S
1       Jane       Doe   28  Canada   65000       J    D
2       John       Doe   42     USA   95000       J    D
3      Sarah     Smith   19     USA   50000       S    S
4       Mike   Johnson   31     USA   72000       M    J
5       Emma     Brown   24     USA   60000       E    B

In [120]:
def salute(x):
    return 'Hello ' + x

df['greeting']=df['FIRST_NAME'].apply(salute)
df

,FIRST_NAME,LAST_NAME,AGE,COUNTRY,SALARY,initial,cred,greeting,age_group
0,Corey,Schafer,35,USA,85000,C,S,Hello Corey,Adult
1,Jane,Doe,28,Canada,65000,J,D,Hello Jane,Young
2,John,Doe,42,USA,95000,J,D,Hello John,Adult
3,Sarah,Smith,19,USA,50000,S,S,Hello Sarah,Young
4,Mike,Johnson,31,USA,72000,M,J,Hello Mike,Adult
5,Emma,Brown,24,USA,60000,E,B,Hello Emma,Young

In [119]:
def youth(x):
    if x < 30:
         return 'Young'
    else:
         return 'Adult'

df['age_group']=df['AGE'].apply(youth)
df

  FIRST_NAME LAST_NAME  AGE COUNTRY  SALARY initial cred    greeting age_group
0      Corey   Schafer   35     USA   85000       C    S  HelloCorey     Adult
1       Jane       Doe   28  Canada   65000       J    D   HelloJane     Young
2       John       Doe   42     USA   95000       J    D   HelloJohn     Adult
3      Sarah     Smith   19     USA   50000       S    S  HelloSarah     Young
4       Mike   Johnson   31     USA   72000       M    J   HelloMike     Adult
5       Emma     Brown   24     USA   60000       E    B   HelloEmma     Young

In [126]:
def incentives(x):
    if x >= 80000:
        return  10000
    else: 
        return  5000
         
    
df['bonus'] =df['SALARY'].apply(incentives)
df

,FIRST_NAME,LAST_NAME,AGE,COUNTRY,SALARY,initial,cred,greeting,age_group,bonus
0,Corey,Schafer,35,USA,85000,C,S,Hello Corey,Adult,10000
1,Jane,Doe,28,Canada,65000,J,D,Hello Jane,Young,5000
2,John,Doe,42,USA,95000,J,D,Hello John,Adult,10000
3,Sarah,Smith,19,USA,50000,S,S,Hello Sarah,Young,5000
4,Mike,Johnson,31,USA,72000,M,J,Hello Mike,Adult,5000
5,Emma,Brown,24,USA,60000,E,B,Hello Emma,Young,5000

In [127]:
#name length
def length(x):
    return len(x)

df['name_length'] = df['FIRST_NAME'].apply(length)
df

,FIRST_NAME,LAST_NAME,AGE,COUNTRY,SALARY,initial,cred,greeting,age_group,bonus,name_length
0,Corey,Schafer,35,USA,85000,C,S,Hello Corey,Adult,10000,5
1,Jane,Doe,28,Canada,65000,J,D,Hello Jane,Young,5000,4
2,John,Doe,42,USA,95000,J,D,Hello John,Adult,10000,4
3,Sarah,Smith,19,USA,50000,S,S,Hello Sarah,Young,5000,5
4,Mike,Johnson,31,USA,72000,M,J,Hello Mike,Adult,5000,4
5,Emma,Brown,24,USA,60000,E,B,Hello Emma,Young,5000,4

In [ ]:
#Mapping country id
mapping= {
    'USA':1,
    'Canada':2,
    'UK':3
}

df['country_id']=df['COUNTRY'].map(mapping)
df

,FIRST_NAME,LAST_NAME,AGE,COUNTRY,SALARY,initial,cred,greeting,age_group,bonus,name_length,country_id
0,Corey,Schafer,35,USA,85000,C,S,Hello Corey,Adult,10000,5,1
1,Jane,Doe,28,Canada,65000,J,D,Hello Jane,Young,5000,4,2
2,John,Doe,42,USA,95000,J,D,Hello John,Adult,10000,4,1
3,Sarah,Smith,19,USA,50000,S,S,Hello Sarah,Young,5000,5,1
4,Mike,Johnson,31,USA,72000,M,J,Hello Mike,Adult,5000,4,1
5,Emma,Brown,24,USA,60000,E,B,Hello Emma,Young,5000,4,1

In [129]:
#mapping nicknames
mapped= {
    'Corey': 'Core',
    'Jane': 'J',
    'John': 'Johnny',
    'Sarah': 'Sar',
    'Mike': 'Mikey',
    'Emma': 'Em'
}
df['nicknames']=df['FIRST_NAME'].map(mapped)
df

,FIRST_NAME,LAST_NAME,AGE,COUNTRY,SALARY,initial,cred,greeting,age_group,bonus,name_length,country_id,nicknames
0,Corey,Schafer,35,USA,85000,C,S,Hello Corey,Adult,10000,5,1,Core
1,Jane,Doe,28,Canada,65000,J,D,Hello Jane,Young,5000,4,2,J
2,John,Doe,42,USA,95000,J,D,Hello John,Adult,10000,4,1,Johnny
3,Sarah,Smith,19,USA,50000,S,S,Hello Sarah,Young,5000,5,1,Sar
4,Mike,Johnson,31,USA,72000,M,J,Hello Mike,Adult,5000,4,1,Mikey
5,Emma,Brown,24,USA,60000,E,B,Hello Emma,Young,5000,4,1,Em

In [132]:
#Replace
replaced = {
    'Core': 'Cora',
    'J': 'Ja',
    'Johnny': 'Joh',
    'Sar': 'Sari',
    'Mikey': 'Mikel',
    'Em': 'Emo'

}
df['nicknames']=df['nicknames'].replace(replaced)
df

,FIRST_NAME,LAST_NAME,AGE,COUNTRY,SALARY,initial,cred,greeting,age_group,bonus,name_length,country_id,nicknames
0,Corey,Schafer,35,USA,85000,C,S,Hello Corey,Adult,10000,5,1,Cora
1,Jane,Doe,28,Canada,65000,J,D,Hello Jane,Young,5000,4,2,Ja
2,John,Doe,42,USA,95000,J,D,Hello John,Adult,10000,4,1,Joh
3,Sarah,Smith,19,USA,50000,S,S,Hello Sarah,Young,5000,5,1,Sari
4,Mike,Johnson,31,USA,72000,M,J,Hello Mike,Adult,5000,4,1,Mikel
5,Emma,Brown,24,USA,60000,E,B,Hello Emma,Young,5000,4,1,Emo

In [ ]:
vdd