In [2]:
import pandas as pd

In [3]:
people = {
    "first": ["Corey", "Jane", "John", "Sarah", "Mike", "Emma"],
    "last": ["Schafer", "Doe", "Doe", "Smith", "Johnson", "Brown"],
    "age": [35, 28, 42, 19, 31, 24],
    "country": ["USA", "Canada", "USA", "UK", "Canada", "USA"],
    "salary": [85000, 65000, 95000, 30000, 72000, 55000]
}

In [31]:
df = pd.DataFrame(people)
df

   first     last  age country  salary
0  Corey  Schafer   35     USA   85000
1   Jane      Doe   28  Canada   65000
2   John      Doe   42     USA   95000
3  Sarah    Smith   19      UK   30000
4   Mike  Johnson   31  Canada   72000
5   Emma    Brown   24     USA   55000

In [ ]:
#REN

  FIRST NAME LAST NAME YOUTH    HOME MUNYUN
0      Corey   Schafer    35     USA  85000
1       Jane       Doe    28  Canada  65000
2       John       Doe    42     USA  95000
3      Sarah     Smith    19      UK  30000
4       Mike   Johnson    31  Canada  72000
5       Emma     Brown    24     USA  55000

In [29]:
#CHANGING COLUMN NAMES TO lowercase

In [28]:
#ChANGING THE COLUMN NAMES FROM UNDERSCORE TO SPACE WHERE WANTEDd

Index(['first', 'last', 'age', 'country', 'salary'], dtype='object')